version: "3.2"
services:
  nodejs:
    restart: always
    build: 
      context: .
    image: dpshetty29/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=antibrnd-mysql-app
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=referral_system
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:5000"
    container_name: antibrnd-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=referral_system
    container_name: antibrnd-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=antibrnd-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: antibrnd-phpmyadmin-app
networks:
  frontend:
  backend:
